### ISSUE TITLE
Register + login API route (POST requests) 

### ISSUE THREAD

**Issue by skassam21** [hatchways/team-daffodil#7]
Adding user model (username (unique), email, encrypted password (bcrypt)), add profile pic, location, and description to the user model
Register route
 - Validate email, username is unique, and that password / confirm password are the same 
- Create a user, generate a JWT token, and will the serve token to the front-end 
Login route
- Verifying of the password (bcyrpt.compare method)

**Comment by alaindavis90** [comment]
"Validate email, username is unique, and that password / confirm password are the same" feature has been implemented
